function PARAMS = ImportParamFile_xls(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DECPARAMS = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DECPARAMS = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DECPARAMS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DecPARAMS = importfile("/Users/stuartmcknight/Dropbox/SARS-CoV-2-Infection-Computational-Model/Model_2_InnateImmune/SpeciesParameterConventions/24Dec_PARAMS.xls", "Sheet1", [1, 56]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Dec-2020 18:35:14

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 56];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":H" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Reaction_Name", "Reaction_Index", "RateConstantName", "RateEquation", "ChemicalEquation", "Value", "Units", "Sources"];
opts.VariableTypes = ["string", "string", "categorical", "categorical", "string", "double", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Reaction_Name", "Reaction_Index", "ChemicalEquation", "Units", "Sources"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Reaction_Name", "Reaction_Index", "RateConstantName", "RateEquation", "ChemicalEquation", "Units", "Sources"], "EmptyFieldRule", "auto");

% Import the data
PARAMS = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    PARAMS = [PARAMS; tb]; %#ok<AGROW>
end

end