function Species = ImportSpeciesFile_csv(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DECSPECIES = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  DECSPECIES = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  DecSpecies = importfile("/Users/stuartmcknight/Dropbox/SARS-CoV-2-Infection-Computational-Model/Model_2_InnateImmune/SpeciesParameterConventions/25Dec_Species.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Dec-2020 07:32:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Species_Index", "Species_Name", "Model_Name", "Initial_Amount", "Range", "Units", "Constant_Amount", "Boundary_Condition", "Type", "Compartment_Type", "Compartment"];
opts.VariableTypes = ["double", "string", "string", "double", "string", "string", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Species_Name", "Model_Name", "Range", "Units"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Species_Name", "Model_Name", "Range", "Units", "Constant_Amount", "Boundary_Condition", "Type", "Compartment_Type", "Compartment"], "EmptyFieldRule", "auto");

% Import the data
Species = readtable(filename, opts);

end