function PARAMS = ImportParamfile_xlsx(workbookFile, sheetName, dataLines)
        %IMPORTFILE Import data from a spreadsheet
        %  PARAMS = IMPORTFILE(FILE) reads data from the first worksheet in the
        %  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
        %  table.
        %
        %  PARAMS = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
        %
        %  PARAMS = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
        %  worksheet for the specified row interval(s). Specify DATALINES as a
        %  positive scalar integer or a N-by-2 array of positive scalar integers
        %  for dis-contiguous row intervals.
        %
        %  Example:
        %  PARAMS = importfile("/Users/stuartmcknight/Dropbox/SARS-CoV-2-Infection-Computational-Model/Model_2_InnateImmune/PARAMS.xlsx", "Sheet1", [2, 59]);
        %
        %  See also READTABLE.
        %
        % Auto-generated by MATLAB on 04-Nov-2020 22:35:55
        
        %% Input handling
        
        % If no sheet is specified, read first sheet
        if nargin == 1 || isempty(sheetName)
            sheetName = 1;
        end
        
        % If row start and end points are not specified, define defaults
        if nargin <= 2
            dataLines = [2, 59];
        end
        
        %% Set up the Import Options and import the data
        opts = spreadsheetImportOptions("NumVariables", 9);
        
        % Specify sheet and range
        opts.Sheet = sheetName;
        opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);
        
        % Specify column names and types
        opts.VariableNames = ["Reaction_Name", "Reaction_Index", "RateConstantName", "RateEquation", "ChemicalEquation", "Value", "Units", "Sources", "VarName9"];
        opts.VariableTypes = ["categorical", "string", "string", "string", "string", "string", "string", "string", "string"];
        
        % Specify variable properties
        opts = setvaropts(opts, ["Reaction_Index", "Value", "Units", "Sources"], "WhitespaceRule", "preserve");
        opts = setvaropts(opts, ["Reaction_Name", "Reaction_Index", "RateConstantName", "RateEquation", "ChemicalEquation", "Value", "Units", "Sources", "VarName9"], "EmptyFieldRule", "auto");
        
        % Import the data
        PARAMS = readtable(workbookFile, opts, "UseExcel", false);
        
        for idx = 2:size(dataLines, 1)
            opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
            tb = readtable(workbookFile, opts, "UseExcel", false);
            PARAMS = [PARAMS; tb]; %#ok<AGROW>
        end
        
end
