function Species = ImportSpeciesFile_xlsx(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DECSPECIES = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DECSPECIES = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DECSPECIES = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DecSpecies = importfile("/Users/stuartmcknight/Dropbox/SARS-CoV-2-Infection-Computational-Model/Model_2_InnateImmune/SpeciesParameterConventions/25Dec_Species.xlsx", "Sheet1", [2, 46]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Dec-2020 07:21:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 46];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 11);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":K" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Species_Index", "Species_Name", "Model_Name", "Initial_Amount", "Range", "Units", "Constant_Amount", "Boundary_Condition", "Type", "Compartment_Type", "Compartment"];
opts.VariableTypes = ["string", "string", "string", "double", "string", "string", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Species_Index", "Species_Name", "Model_Name", "Range", "Units"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Species_Index", "Species_Name", "Model_Name", "Range", "Units", "Constant_Amount", "Boundary_Condition", "Type", "Compartment_Type", "Compartment"], "EmptyFieldRule", "auto");

% Import the data
Species = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":K" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Species = [Species; tb]; %#ok<AGROW>
end

end